import { prisma } from "@/lib/prisma";

const templates = [
  {
    id: "insta-quote-001",
    name: "Minimalist Quote",
    thumbnail:
      "https://images.unsplash.com/photo-1460398495418-62c9b5d79fbf?auto=format&fit=crop&w=400&q=80",
    width: 1080,
    height: 1080,
    category: "Social Media",
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: "#ffffff",
          selectable: false,
        },
        {
          type: "i-text",
          left: 540,
          top: 400,
          originX: "center",
          fill: "#000000",
          text: "STAY\nHUMBLE",
          fontSize: 80,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 540,
          top: 550,
          originX: "center",
          fill: "#000000",
          text: "Work hard in silence.",
          fontSize: 30,
          opacity: 0.7,
        },
      ],
    },
  },
  {
    id: "dark-sale-002",
    name: "Dark Mode Sale",
    thumbnail:
      "https://img.freepik.com/free-vector/gradient-dark-mode-app-template_52683-118059.jpg?w=400",
    width: 1080,
    height: 1080,
    category: "Social Media",
    isPro: true,
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: "#1a1a1a",
          selectable: false,
        },
        {
          type: "i-text",
          left: 540,
          top: 400,
          originX: "center",
          fill: "#ffffff",
          text: "50% OFF\nEVERYTHING",
          fontSize: 80,
          fontWeight: "bold",
          textAlign: "center",
        },
      ],
    },
  },
  {
    id: "neon-story-003",
    name: "Neon Story",
    thumbnail:
      "https://image.mux.com/wSKER3RbSAx9dKaSUtDNZKlskW9i8jPYOUr4lJvOI02Q/thumbnail.webp?time=0",
    width: 1080,
    height: 1920,
    category: "Social Media",
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 1080,
          height: 1920,
          fill: "#000000",
          selectable: false,
        },
        {
          type: "i-text",
          left: 540,
          top: 600,
          originX: "center",
          fill: "#00ff00",
          text: "VIBE\nCHECK",
          fontSize: 100,
          fontWeight: "bold",
        },
      ],
    },
  },

  {
    id: "corp-biz-004",
    name: "Modern Business Card",
    thumbnail:
      "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/blue-business-card-for-shop-design-template-7f50eda7b89d12b8b07a535c5a38530d_screen.jpg?ts=1743595539",
    width: 1050,
    height: 600,
    category: "Business",
    isPro: false,
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 1050,
          height: 600,
          fill: "#ffffff",
          selectable: false,
        },
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 300,
          height: 600,
          fill: "#1a1a1a",
        },
        {
          type: "i-text",
          left: 350,
          top: 200,
          fill: "#1a1a1a",
          text: "ALEX STEVENS",
          fontSize: 40,
          fontWeight: "bold",
          fontFamily: "sans-serif",
        },
        {
          type: "i-text",
          left: 350,
          top: 250,
          fill: "#8b5cf6",
          text: "Creative Director",
          fontSize: 20,
          fontFamily: "sans-serif",
        },
        {
          type: "i-text",
          left: 350,
          top: 400,
          fill: "#666666",
          text: "alex@example.com\n+1 234 567 890\://yourwebsite.com",
          fontSize: 18,
          lineHeight: 1.5,
        },
      ],
    },
  },
  {
    id: "pitch-deck-005",
    name: "Startup Pitch Slide",
    thumbnail:
      "https://visme.co/blog/wp-content/uploads/2024/08/15-Successful-Startup-Pitch-Deck-ExamplesTipsTemplates-Thumbnail.jpg",
    width: 1920,
    height: 1080,
    category: "Presentation",
    isPro: true,
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 1920,
          height: 1080,
          fill: "#f8fafc",
          selectable: false,
        },
        {
          type: "rect",
          left: 100,
          top: 100,
          width: 10,
          height: 150,
          fill: "#8b5cf6",
        },
        {
          type: "i-text",
          left: 140,
          top: 100,
          fill: "#0f172a",
          text: "THE PROBLEM",
          fontSize: 120,
          fontWeight: "900",
          fontFamily: "sans-serif",
        },
        {
          type: "i-text",
          left: 140,
          top: 350,
          fill: "#475569",
          text: "Describe the core challenge your startup is solving.\nKeep it concise and high-impact.",
          fontSize: 45,
          width: 1000,
          splitByGrapheme: true,
          lineHeight: 1.4,
        },
        {
          type: "circle",
          left: 1400,
          top: 540,
          radius: 200,
          fill: "#e2e8f0",
          originX: "center",
          originY: "center",
        },
        {
          type: "i-text",
          left: 1400,
          top: 540,
          originX: "center",
          originY: "center",
          fill: "#94a3b8",
          text: "IMAGE\nMOCKUP",
          fontSize: 30,
          fontWeight: "bold",
        },
      ],
    },
  },

  {
    id: "event-flyer-006",
    name: "Corporate Event Flyer",
    thumbnail:
      "https://brandpacks.com/wp-content/uploads/edd/2026/03/social-media-quote-post-templates-canva-ai-psd-eps-02.jpg",
    width: 794,
    height: 1123,
    category: "Marketing",
    isPro: false,
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 794,
          height: 1123,
          fill: "#ffffff",
          selectable: false,
        },
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 794,
          height: 400,
          fill: "#0f172a",
        },
        {
          type: "i-text",
          left: 397,
          top: 150,
          originX: "center",
          fill: "#ffffff",
          text: "ANNUAL\nCONFERENCE",
          fontSize: 70,
          fontWeight: "900",
          textAlign: "center",
        },
        {
          type: "i-text",
          left: 397,
          top: 300,
          originX: "center",
          fill: "#38bdf8",
          text: "INNOVATION 2025",
          fontSize: 24,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 100,
          top: 480,
          fill: "#334155",
          text: "JOIN US FOR A DAY OF\nNETWORKING & GROWTH",
          fontSize: 32,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 100,
          top: 600,
          fill: "#64748b",
          text: "• Expert Keynote Speakers\n• Interactive Workshops\n• Networking Lunch\n• Innovation Awards",
          fontSize: 20,
          lineHeight: 2,
        },
        {
          type: "rect",
          left: 0,
          top: 1000,
          width: 794,
          height: 123,
          fill: "#f1f5f9",
        },
        {
          type: "i-text",
          left: 397,
          top: 1060,
          originX: "center",
          fill: "#0f172a",
          text: "REGISTER AT ://yoursite.com",
          fontSize: 18,
          fontWeight: "bold",
        },
      ],
    },
  },
  {
    id: "clean-resume-007",
    name: "Modern Resume",
    thumbnail:
      "https://themes.3rdwavemedia.com/wp-content/uploads/2023/02/risen-sketch-dark-theme-resume-template-thumbnail.png",
    width: 794,
    height: 1123,
    category: "Resume",
    isPro: true,
    json: {
      version: "5.3.0",
      objects: [
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 794,
          height: 1123,
          fill: "#ffffff",
          selectable: false,
        },
        {
          type: "rect",
          left: 0,
          top: 0,
          width: 250,
          height: 1123,
          fill: "#f8fafc",
        },
        {
          type: "circle",
          left: 125,
          top: 150,
          radius: 60,
          fill: "#e2e8f0",
          originX: "center",
        },
        {
          type: "i-text",
          left: 280,
          top: 100,
          fill: "#0f172a",
          text: "JONATHAN DOE",
          fontSize: 48,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 280,
          top: 160,
          fill: "#8b5cf6",
          text: "SENIOR FULL STACK DEVELOPER",
          fontSize: 18,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 280,
          top: 250,
          fill: "#0f172a",
          text: "EXPERIENCE",
          fontSize: 22,
          fontWeight: "bold",
        },
        {
          type: "rect",
          left: 280,
          top: 280,
          width: 450,
          height: 2,
          fill: "#e2e8f0",
        },
        {
          type: "i-text",
          left: 280,
          top: 310,
          fill: "#334155",
          text: "Tech Solutions Inc. | 2020 - Present\nImplemented high-scale React architectures\nand managed AWS infrastructure.",
          fontSize: 16,
          width: 450,
          splitByGrapheme: true,
          lineHeight: 1.5,
        },
        {
          type: "i-text",
          left: 50,
          top: 250,
          fill: "#0f172a",
          text: "CONTACT",
          fontSize: 18,
          fontWeight: "bold",
        },
        {
          type: "i-text",
          left: 50,
          top: 290,
          fill: "#64748b",
          text: "hello@doe.com\n+1 555 0123\nNew York, NY",
          fontSize: 14,
          lineHeight: 1.8,
        },
      ],
    },
  },
];

async function main() {
  console.log("Seeding templates...");
  for (const template of templates) {
    await prisma.template.upsert({
      where: { id: template.id },
      update: {},
      create: template,
    });
  }
  console.log("Seeding finished!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
